// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9tj0H9arl6jYo2Q4pV8ynDcTk0Nisdy0',
    appId: '1:214713870561:web:e3a5a1ae3235aaaba6efa0',
    messagingSenderId: '214713870561',
    projectId: 'authtutorial-b4bd9',
    authDomain: 'authtutorial-b4bd9.firebaseapp.com',
    storageBucket: 'authtutorial-b4bd9.appspot.com',
    measurementId: 'G-FDKHLNHPCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfU3dneohG8txB2huYKGLSvORi-D2cHjE',
    appId: '1:214713870561:android:2ef2bd357c01305da6efa0',
    messagingSenderId: '214713870561',
    projectId: 'authtutorial-b4bd9',
    storageBucket: 'authtutorial-b4bd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ghWGV6Hgu64tU6RQwlhnEcL7WEo_kys',
    appId: '1:214713870561:ios:e43b9c12e432b606a6efa0',
    messagingSenderId: '214713870561',
    projectId: 'authtutorial-b4bd9',
    storageBucket: 'authtutorial-b4bd9.appspot.com',
    iosClientId: '214713870561-pf9drshk5s4ps1tvebkqmb6sp76nd9ld.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5ghWGV6Hgu64tU6RQwlhnEcL7WEo_kys',
    appId: '1:214713870561:ios:be60345480533895a6efa0',
    messagingSenderId: '214713870561',
    projectId: 'authtutorial-b4bd9',
    storageBucket: 'authtutorial-b4bd9.appspot.com',
    iosClientId: '214713870561-v9o7otjmjg3jknm82f3f51v15j04vt5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationApp.RunnerTests',
  );
}
